### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by foopledoop**
this took 7 minutes to load the webpage for the PR jfc

### CODE REVIEW

**Comment by foopledoop** [comment]
the problem seems to be that github is not optimized to preview 200+ images in one PR. instead of lazy-loading, it just loads the entire fucking thing at once, and is not good at it

**Review by i-am-a-dev3 — CHANGES_REQUESTED** [review]
lmao rofl rofl dingus dengue fever malaria

**Review by hekalet — CHANGES_REQUESTED** [review]
Please do not push changes into main. Instead do it in the new branch.

**Comment by foopledoop** [comment]
I AM GOING TO PUnCH WHOEVER DESIGNED THIS SITE IN THE FACE BECAUSE THIS IS SO FUCKING STUPID GOOGLE TELLS ME THERES A DROP DOWN FOR THE BRANCHES BUT THATS ONLY WHEN YOU'RE VIEWING A REPO AND THIS COMMENT BOX HAS LIKE 2 SECONDS OF INPUT LAG AND THERES NO CLEAR WAY TO CHANGE A PULL REQUEST OR ANYTHING INDICATING IF YOU CAN OR CANT AND IT TOOK 7 MINUTES TO LOAD A SINGLE WEBPAGE
1. what's the name of the new branch?
2. how can i change this pr to push there instead of main?

**Comment by hekalet** [comment]
https://github.com/hekalet/BreakRoom/tree/new-game-branch

The branch is "new-game-branch".

**Pull request closed without merging**
